graph LR
  src/App.tsx -- imports --> ./i18n
  src/App.tsx -- imports --> ./App
  src/App.tsx -- imports --> ./index.css
  src/main.tsx -- imports --> ./App
  src/main.tsx -- imports --> ./i18n
  src/main.tsx -- imports --> ./index.css